### ISSUE TITLE
How to test one's own image

### ISSUE THREAD

**Issue by EvenGu** [princeton-vl/pytorch_stacked_hourglass#1]
Hi, there,

I want to run the model (checkpoint.pt) on my own images and make predictions. How should I do that? 
I see the test.py use the configuration of the train.py, which takes in the jpeg files in the data/MPII/images. 
Do I simply change the img_dir in the ref.py 
img_dir = 'data/MPII/images' to path_to_my_images?

Thank you for your help!

**Comment by crockwell** [comment]
Yes, you should be able to make predictions on other images by putting them in data/MPII/images. Keep in mind that the current pipeline loads filenames from the "train.h5"/"val.h5"/"test.h5" in data/MPII/annot. See line ~179 in test.py. Also, keep in mind there are a few other things being loaded from these files for cropping, e.g. center and scale. The model performs best when people are centered and at a scale consistent with MPII.
