### ISSUE TITLE
quarter shift calculation question

### ISSUE THREAD

**Issue by dmitrysarov** [princeton-vl/pytorch_stacked_hourglass#15]
https://github.com/princeton-vl/pytorch_stacked_hourglass/blob/64907788e4c69616aac9ab044ae26fc010ed89c3/utils/group.py#L41
As i understood there is no actually second peak search, the shift is just performed in the direction of skew of distribution, right?

**Comment by crockwell** [comment]
can you clarify what you mean by "second peak search"? As I understand, I think you are correct: the shifts are just small sub-pixel changes based on location in image, which is motivated by skew in distribution (or similar idea).

**Comment by dmitrysarov** [comment]
I mean - to search real local isolated peak, by mean, for example, https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_peak_local_max.html

**Comment by crockwell** [comment]
No, we don't use a function like that.
