### ISSUE TITLE
How to train on custom dataset like MSCOCO?

### ISSUE THREAD

**Issue by WinstonDeng** [princeton-vl/pytorch_stacked_hourglass#16]
Hi, thanks for your great work!
I'd like to train this model on COCO dataset. How to load custom dataset and build my config for training? 
Looking forward to your advice.

**Comment by crockwell** [comment]
Thanks! Sure: our multi-person pose code (https://github.com/princeton-vl/pose-ae-train) uses COCO and has a really similar structure to this code, so I'd definitely recommend starting from there. data/coco_pose/ref.py will have a lot of helpful functions I think!

**Comment by WinstonDeng** [comment]
@crockwell thanks for your help!

**Comment by crockwell** [comment]
No problem!

**Comment by NiranthS** [comment]
@WinstonDeng  were you able to make ref.py file for the COCO dataset. If yes, can you please share it?
