### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 10.76 GiB total capacity; 9.87 GiB already allocated; 34.44 MiB free; 9.89 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by Scheng-xiang** [princeton-vl/pytorch_stacked_hourglass#18]
why it happend?

**Comment by Scheng-xiang** [comment]
My gpu is 2080ti and have 11g memory, does it need more than 11g memory to trian or something was  wrong happend?

**Comment by crockwell** [comment]
Depends on your batch size. For the full 8HG network & batch size of 16 or 32, you'll probably need multiple GPUs.
