### ISSUE TITLE
When I try to implement the 'train.py' there is a suspicious issues....

### ISSUE THREAD

**Issue by MINZLATAN** [princeton-vl/pytorch_stacked_hourglass#28]
I tried to run your 'train.py' and it is showed like this....
I think it is working....but is that an error which is shown as a '0%| | blah blah ~~' before the 'start train pose' and ' start valid pose' ??
![image](https://user-images.githubusercontent.com/57806093/108665884-5247c700-7519-11eb-9570-533ec6de2a59.png)

I can see the checkpoint is saved after every epoch is ended. and I can find the checkpoint file too.
But not sure I'm doing right way or the problem is happening.

Thanks in advance.
@crockwell @jiang-du

**Comment by crockwell** [comment]
This sometimes happens when using tqdm
