### ISSUE TITLE
Resize image and move keypoints

### ISSUE THREAD

**Issue by zenghy96** [princeton-vl/pytorch_stacked_hourglass#3]
When we use Dataloader via PyTorch, all images should have same size in a batch, so how can I move the labeled keypoints to right position after resizing the image? Thanks!

**Comment by zenghy96** [comment]
Maybe you did't use the 'Dataloader'  in PyTorch?

**Comment by crockwell** [comment]
Correct -- they will have the same size, currently set to 256,256. During training, keypoints will accordingly be warped using utils.img.kpt_affine (you can see this called in data/MPII/dp.py line 88). Currently, the program is setup to return heatmaps based on these keypoints, but you can easily modify to also return keypoints. During inference, we do the opposite: map keypoints predicted on 256, 256 size to the original image. See line 15 of test.py for details.

**Comment by zhoujinhai** [comment]
> Correct -- they will have the same size, currently set to 256,256. During training, keypoints will accordingly be warped using utils.img.kpt_affine (you can see this called in data/MPII/dp.py line 88). Currently, the program is setup to return heatmaps based on these keypoints, but you can easily modify to also return keypoints. During inference, we do the opposite: map keypoints predicted on 256, 256 size to the original image. See line 15 of test.py for details.

Thanks your code, I has a question that is the key point coordinate on the 256*256image or the 64*64 image
