### ISSUE TITLE
Is there any reason for choosing Nearest Neighbor method for interpolation on Upsampling?

### ISSUE THREAD

**Issue by demul** [princeton-vl/pytorch_stacked_hourglass#30]
I think maybe you tested other methods and finally choose best one.
Thinking about the situations that Nearest Neighbor is superior to others, the first thing that comes to my mind is, when the data is (nearly) categorical. 
Interpolating data whose distribution is categorical with Linear or Spline method(or something like that) makes data ambiguous.
in that cases, NN is better.
that's why I think some data in intermediate activation map will be (at least partially) categorical. 

I'm so curious about whether you carried a study for comparing interpolation methods, and whether you got any insight about  neural activation map distribution.
It will be big pleasure if u share your insight about this idea for me.

Thank you for publishing a good research paper.

**Comment by crockwell** [comment]
Thanks for the question. I can't personally comment on the empirical difference between upsampling choice in this network, but nearest neighbor is commonly used (e.g. mask r-cnn uses it), and is the default on pytorch.

But these are good questions! I don't have many more answers but they are certainly interesting research questions.

**Comment by demul** [comment]
Thank u.
Good luck on your research!
