### ISSUE TITLE
How to get the h5py files from the raw annotations?

### ISSUE THREAD

**Issue by BIGJUN777** [princeton-vl/pytorch_stacked_hourglass#33]
Hello, thank you for your nice work.

I wanna know how to get the h5py data file (test.h5, train.h5, vaild.h5) from the raw annotation files in MPII dataset. Or can you explain what those data listed in [ref.py](https://github.com/princeton-vl/pytorch_stacked_hourglass/blob/ed91059e874f35089dd3a8e692fa895929785b91/data/MPII/ref.py#L26) (such as: center, scale, part and so on ) in the h5py file mean?

**Comment by crockwell** [comment]
Thanks. Yeah that comes essentially from MPII. I'd check out their work. Also https://github.com/akanazawa/hmr/blob/master/src/datasets/mpii_to_tfrecords.py has some really detailed code that might shed some light on this. It's basically for cropping around each individual person.

**Comment by BIGJUN777** [comment]
Cool. Thank you for your nice reply.
