### ISSUE TITLE
2D joints as outputs

### ISSUE THREAD

**Issue by dvdblk** [princeton-vl/pytorch_stacked_hourglass#35]
Hello. If I understood correctly, this network outputs a set of 64x64 heatmaps for each joint. However, I would like to get 2D joint keypoints as the output. 

In other words the output size I want would be (16, 2) = 16 times 2D coordinates of each joint.

What should I do in order to get this output from the heatmaps / network? :) 

Thanks!!

**Comment by crockwell** [comment]
You are correct. Actually keypoints are generated via post-processing -- see test.py for details
