### ISSUE TITLE
more details about the annotations

### ISSUE THREAD

**Issue by TheScientist1900** [princeton-vl/pytorch_stacked_hourglass#39]
Hi, I have downloaded the Image files and annotation files on the official website of MPII datasets, but the structure of raw annotation files is different from yours in this project. So I want to ask what‘s the meaning of the field 'center'、'scale’ 、and 'normalize'。Also how the 'normalize' data is captured?

**Comment by crockwell** [comment]
These variables can be a bit confusing. For discussion, I'd recommend poking through the MPII code, as well as seeing the discussion in this issue: https://github.com/princeton-vl/pytorch_stacked_hourglass/issues/19. Also this one: https://github.com/princeton-vl/pytorch_stacked_hourglass/issues/33
