### ISSUE TITLE
Why do we need to predict twice？

### ISSUE THREAD

**Issue by zhoujinhai** [princeton-vl/pytorch_stacked_hourglass#46]
In test.py,  I find forward twice and get tmp1, tmp2. I want to know why you're doing this？
![image](https://github.com/princeton-vl/pytorch_stacked_hourglass/assets/20365125/c3bfe1a5-6807-44cd-9259-63f610ed24ed)

**Comment by crockwell** [comment]
Hey - good catch! So actually running the model on both the image and the flipped image, and averaging the keypoints ends up doing better than just running once. So, it is run twice.

**Comment by zhoujinhai** [comment]
> 

Thanks reploy.
