### ISSUE TITLE
coordinate overlap

### ISSUE THREAD

**Issue by Winnie202** [princeton-vl/pytorch_stacked_hourglass#47]
Thank you for your contribution of the code. I completed the detection of 4 key points according to your code, but the second coordinate and the third coordinate overlap. May I ask why， How to solve this problem

![2023-09-22 18-35-10屏幕截图](https://github.com/princeton-vl/pytorch_stacked_hourglass/assets/86768013/39a6f57a-c713-49c2-992a-7a4e2047a117)

**Comment by crockwell** [comment]
Hi Winnie,

This model was trained on predicting joints in humans. Therefore, I wouldn't expect it to be best for generic detection of keypoints e.g. of a piece of paper. I'd recommend using a generic detection method such as the [YOLO](https://pjreddie.com/darknet/yolo/) line of work.


Regards,
Chris
