### ISSUE TITLE
pretrained model not available

### ISSUE THREAD

**Issue by square-melon** [princeton-vl/pytorch_stacked_hourglass#49]
Hi, thanks for your great work!

I want to estimate 3D pose by stacked hourglass detection, and have a quick demo, the link of 8HG and 2HG pretrained model seem to be expired or unavailable. Can you re-upload it? That will be grateful!

**Comment by crockwell** [comment]
Can you try to copy link and open it in your browser again? I just tried and was able to download

**Comment by square-melon** [comment]
It works. Thanks a lot!
